name = "gallium"
version = "0.1.0"
target = "javascript"

description = "Selenium bindings for Gleam"
repository = { type = "github", user = "matiascr", repo = "gallium" }

[javascript]
typescript_definitions = true

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_fetch = ">= 1.2.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
gleam_otp = ">= 0.16.1 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
